#!/usr/bin/env bash
#
# Regenerate docs/usage-catalog.md and docs/usage-catalog.json.
#
# Scans every repository in the org for references to this repo's composite
# actions and reusable workflows, so a change here can be assessed against its
# real blast radius instead of a guess. Run it before altering any action or
# workflow input.
#
#   ./.github/scripts/build-usage-catalog.sh            # whole org
#   ORG=Some-Other-Org ./.github/scripts/build-usage-catalog.sh
#
# Requires: gh (authenticated), jq.
set -euo pipefail

ORG="${ORG:-Gforce-Innovation-Kft}"
SELF="shared-github-actions"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_JSON="$REPO_ROOT/docs/usage-catalog.json"
OUT_MD="$REPO_ROOT/docs/usage-catalog.md"

command -v gh >/dev/null || { echo "gh is required" >&2; exit 1; }
command -v jq >/dev/null || { echo "jq is required" >&2; exit 1; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
HITS="$WORK/hits.jsonl"
: > "$HITS"

echo "Scanning $ORG for references to $SELF ..." >&2

repos=$(gh repo list "$ORG" --limit 200 --json name,defaultBranchRef \
  --jq '.[] | "\(.name)\t\(.defaultBranchRef.name // "main")"')

while IFS=$'\t' read -r repo branch; do
  [ -n "$repo" ] || continue

  # One tree call per repo beats one contents call per file.
  tree=$(gh api "repos/$ORG/$repo/git/trees/$branch?recursive=1" \
    --jq '.tree[]? | select(.type=="blob") | .path' 2>/dev/null || true)
  [ -n "$tree" ] || continue

  files=$(printf '%s\n' "$tree" | grep -E '^\.github/(workflows|actions)/.*\.ya?ml$' || true)
  [ -n "$files" ] || continue

  while IFS= read -r file; do
    [ -n "$file" ] || continue
    content=$(gh api "repos/$ORG/$repo/contents/$file?ref=$branch" \
      --jq '.content' 2>/dev/null | base64 -d 2>/dev/null || true)
    [ -n "$content" ] || continue

    # `uses:` refs into this repo — captures kind, asset name and the pinned ref.
    # Most files reference nothing; grep exiting 1 there is expected, not fatal.
    refs=$(printf '%s\n' "$content" \
      | grep -oE "$SELF/\.github/(actions|workflows)/[^@\"' ]+@[^\"' ]+" \
      | sort -u || true)
    [ -n "$refs" ] || continue

    printf '%s\n' "$refs" \
      | while IFS= read -r ref; do
          kind=$(printf '%s' "$ref" | sed -E "s#.*/\.github/(actions|workflows)/.*#\1#")
          asset=$(printf '%s' "$ref" | sed -E "s#.*/\.github/(actions|workflows)/([^@]+)@.*#\2#")
          pin=$(printf '%s' "$ref" | sed -E 's#.*@##')
          jq -nc --arg repo "$repo" --arg file "$file" --arg kind "$kind" \
                 --arg asset "$asset" --arg pin "$pin" \
            '{repo:$repo, file:$file, kind:$kind, asset:$asset, ref:$pin}' >> "$HITS"
        done
  done <<< "$files"
done <<< "$repos"

generated_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)

jq -s --arg org "$ORG" --arg at "$generated_at" '
  {
    schemaVersion: 1,
    org: $org,
    generatedAt: $at,
    assets: (
      group_by(.kind + "/" + .asset)
      | map({
          kind:  .[0].kind,
          name:  .[0].asset,
          consumers: (
            group_by(.repo)
            | map({
                repo: .[0].repo,
                references: (map({file, ref}) | unique | sort_by(.file))
              })
            | sort_by(.repo)
          )
        })
      | sort_by(.kind, .name)
    )
  }' "$HITS" > "$OUT_JSON"

# Human/agent readable view of the same data.
{
  echo "# Usage catalog — who consumes this repo"
  echo
  echo "<!-- GENERATED by .github/scripts/build-usage-catalog.sh — do not edit by hand. -->"
  echo
  echo "Every reference to this repo's actions and reusable workflows found across"
  echo "the \`$ORG\` org, newest scan \`$generated_at\`."
  echo
  echo "**Read this before changing an action or workflow.** Removing or renaming an"
  echo "input, an output, or a file listed here breaks the consumers named beside it."
  echo "Regenerate with \`./.github/scripts/build-usage-catalog.sh\`."
  echo
  echo "## Scope and limitations"
  echo
  echo "Know what this does *not* tell you before trusting it as an all-clear:"
  echo
  echo "- **Default branches only.** Consumers on feature branches are invisible here."
  echo "  A workflow that exists only on a feature branch will not appear until merged."
  echo "- **This org only** (\`$ORG\`). Forks and personal repos are not scanned."
  echo "- **Static \`uses:\` refs only.** A reference built at runtime, or one living in"
  echo "  a script rather than a \`uses:\`, is not detected."
  echo "- **The pinned ref matters.** A consumer on \`@v1\` does not see changes on"
  echo "  \`develop\`; one on \`@develop\` is affected the moment you push. Check the"
  echo "  ref column before assuming a change is safe or that it has landed."
  echo

  total=$(jq '[.assets[].consumers[].references[]] | length' "$OUT_JSON")
  assets=$(jq '.assets | length' "$OUT_JSON")
  echo "_$total reference(s) to $assets asset(s)._"
  echo

  jq -r '
    .assets[]
    | "## `" + .name + "` (" + .kind + ")\n"
      + (
          if (.consumers | length) == 0 then
            "No known consumers. Safe to change, but confirm before deleting.\n"
          else
            "| Consumer repo | File | Pinned ref |\n|---|---|---|\n"
            + ([ .consumers[] as $c
                 | $c.references[]
                 | "| `" + $c.repo + "` | `" + .file + "` | `" + .ref + "` |"
               ] | join("\n"))
            + "\n"
          end
        )
  ' "$OUT_JSON"
} > "$OUT_MD"

echo "Wrote $OUT_MD and $OUT_JSON" >&2
jq -r '.assets[] | "  " + .kind + "/" + .name + " -> "
       + ([.consumers[].references[]] | length | tostring) + " reference(s)"' "$OUT_JSON" >&2
